# Generated by Django 3.2.12 on 2022-02-05 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_test1_test2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test1',
        ),
        migrations.DeleteModel(
            name='test2',
        ),
    ]
