# Generated by Django 3.2.12 on 2022-02-06 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220205_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='old_resume',
            field=models.ManyToManyField(related_name='old_resume', to='users.Resume'),
        ),
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserResume', to='users.resume'),
        ),
    ]
